### ISSUE TITLE
Unable to pick up Jira ticket ID when inside parentheses

### ISSUE THREAD

**Issue by pean** [jyggen/pingu#1]
Pingu is unable to pick up in Jira ticket # when written inside parentheses. This works

`!JIRA-1234
`
while this does not

`(!JIRA-1234)`

**Comment by jyggen** [comment]
Fixed in 0ca8ade513ba3c0161b26d8f0b2924e4d565c955 (and bugfixed in 76ca5e7a8e0966684e2215a6ac1d68e254e28ec8 because why test before you push things).
